export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GUEST_ENTER_NAME = 'GUEST_ENTER_NAME';
export const GUEST_SUCCESS = 'GUEST_SUCCESS';
export const GUEST_LOGOUT = 'GUEST_LOGOUT';
export const SET_USER = 'SET_USER';